# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sorting_pb2 as sorting__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sorting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SorterStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.deposit = channel.unary_unary(
                '/esercitazione.gRPC.Sorter/deposit',
                request_serializer=sorting__pb2.Package.SerializeToString,
                response_deserializer=sorting__pb2.Ack.FromString,
                _registered_method=True)
        self.collect = channel.unary_unary(
                '/esercitazione.gRPC.Sorter/collect',
                request_serializer=sorting__pb2.CollectRequest.SerializeToString,
                response_deserializer=sorting__pb2.Package.FromString,
                _registered_method=True)
        self.watchStatus = channel.unary_stream(
                '/esercitazione.gRPC.Sorter/watchStatus',
                request_serializer=sorting__pb2.Empty.SerializeToString,
                response_deserializer=sorting__pb2.Status.FromString,
                _registered_method=True)
        self.listPackage = channel.unary_stream(
                '/esercitazione.gRPC.Sorter/listPackage',
                request_serializer=sorting__pb2.DestinationRequest.SerializeToString,
                response_deserializer=sorting__pb2.Package.FromString,
                _registered_method=True)


class SorterServicer:
    """Missing associated documentation comment in .proto file."""

    def deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def collect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def watchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SorterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.deposit,
                    request_deserializer=sorting__pb2.Package.FromString,
                    response_serializer=sorting__pb2.Ack.SerializeToString,
            ),
            'collect': grpc.unary_unary_rpc_method_handler(
                    servicer.collect,
                    request_deserializer=sorting__pb2.CollectRequest.FromString,
                    response_serializer=sorting__pb2.Package.SerializeToString,
            ),
            'watchStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.watchStatus,
                    request_deserializer=sorting__pb2.Empty.FromString,
                    response_serializer=sorting__pb2.Status.SerializeToString,
            ),
            'listPackage': grpc.unary_stream_rpc_method_handler(
                    servicer.listPackage,
                    request_deserializer=sorting__pb2.DestinationRequest.FromString,
                    response_serializer=sorting__pb2.Package.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'esercitazione.gRPC.Sorter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('esercitazione.gRPC.Sorter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sorter:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esercitazione.gRPC.Sorter/deposit',
            sorting__pb2.Package.SerializeToString,
            sorting__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def collect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esercitazione.gRPC.Sorter/collect',
            sorting__pb2.CollectRequest.SerializeToString,
            sorting__pb2.Package.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def watchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/esercitazione.gRPC.Sorter/watchStatus',
            sorting__pb2.Empty.SerializeToString,
            sorting__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/esercitazione.gRPC.Sorter/listPackage',
            sorting__pb2.DestinationRequest.SerializeToString,
            sorting__pb2.Package.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
