# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sorting.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sorting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsorting.proto\x12\x12\x65sercitazione.gRPC\"\x07\n\x05\x45mpty\"\x15\n\x03\x41\x63k\x12\x0e\n\x06result\x18\x01 \x01(\t\"<\n\x07Package\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08priority\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\"6\n\x0e\x43ollectRequest\x12\x10\n\x08priority\x18\x01 \x01(\t\x12\x12\n\ncourier_id\x18\x02 \x01(\t\"K\n\x06Status\x12\x15\n\rstandard_size\x18\x01 \x01(\x05\x12\x14\n\x0c\x65xpress_size\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_sorted\x18\x03 \x01(\x05\")\n\x12\x44\x65stinationRequest\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t2\xb3\x02\n\x06Sorter\x12?\n\x07\x64\x65posit\x12\x1b.esercitazione.gRPC.Package\x1a\x17.esercitazione.gRPC.Ack\x12J\n\x07\x63ollect\x12\".esercitazione.gRPC.CollectRequest\x1a\x1b.esercitazione.gRPC.Package\x12\x46\n\x0bwatchStatus\x12\x19.esercitazione.gRPC.Empty\x1a\x1a.esercitazione.gRPC.Status0\x01\x12T\n\x0blistPackage\x12&.esercitazione.gRPC.DestinationRequest\x1a\x1b.esercitazione.gRPC.Package0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sorting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=37
  _globals['_EMPTY']._serialized_end=44
  _globals['_ACK']._serialized_start=46
  _globals['_ACK']._serialized_end=67
  _globals['_PACKAGE']._serialized_start=69
  _globals['_PACKAGE']._serialized_end=129
  _globals['_COLLECTREQUEST']._serialized_start=131
  _globals['_COLLECTREQUEST']._serialized_end=185
  _globals['_STATUS']._serialized_start=187
  _globals['_STATUS']._serialized_end=262
  _globals['_DESTINATIONREQUEST']._serialized_start=264
  _globals['_DESTINATIONREQUEST']._serialized_end=305
  _globals['_SORTER']._serialized_start=308
  _globals['_SORTER']._serialized_end=615
# @@protoc_insertion_point(module_scope)
