# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\"esercitazione_5_gRPC_Flask_MongoDb\"\x07\n\x05\x45mpty\".\n\x06Sensor\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\"3\n\x0bMeanRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\" \n\rStringMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe2\x01\n\nStatistics\x12\x65\n\ngetSensors\x12).esercitazione_5_gRPC_Flask_MongoDb.Empty\x1a*.esercitazione_5_gRPC_Flask_MongoDb.Sensor0\x01\x12m\n\x07getMean\x12/.esercitazione_5_gRPC_Flask_MongoDb.MeanRequest\x1a\x31.esercitazione_5_gRPC_Flask_MongoDb.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=56
  _globals['_EMPTY']._serialized_end=63
  _globals['_SENSOR']._serialized_start=65
  _globals['_SENSOR']._serialized_end=111
  _globals['_MEANREQUEST']._serialized_start=113
  _globals['_MEANREQUEST']._serialized_end=164
  _globals['_STRINGMESSAGE']._serialized_start=166
  _globals['_STRINGMESSAGE']._serialized_end=198
  _globals['_STATISTICS']._serialized_start=201
  _globals['_STATISTICS']._serialized_end=427
# @@protoc_insertion_point(module_scope)
