// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sensor.proto
// Protobuf Java Version: 4.31.1

package sensor;

@com.google.protobuf.Generated
public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
