// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sensor.proto
// Protobuf Java Version: 4.31.1

package sensor;

@com.google.protobuf.Generated
public final class Sensor {
  private Sensor() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Sensor.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensor_Reading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensor_Reading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensor_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensor_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensor_SensorQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensor_SensorQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensor_Stats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensor_Stats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sensor.proto\022\006sensor\"L\n\007Reading\022\021\n\tsen" +
      "sor_id\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\r\n\005value\030\003 \001(" +
      "\001\022\021\n\ttimestamp\030\004 \001(\005\"(\n\003Ack\022\020\n\010accepted\030" +
      "\001 \001(\010\022\017\n\007message\030\002 \001(\t\"5\n\013SensorQuery\022\021\n" +
      "\tsensor_id\030\001 \001(\t\022\023\n\013max_results\030\002 \001(\005\"G\n" +
      "\005Stats\022\021\n\tsensor_id\030\001 \001(\t\022\r\n\005count\030\002 \001(\005" +
      "\022\017\n\007average\030\003 \001(\001\022\013\n\003max\030\004 \001(\0012\252\001\n\tSenso" +
      "rHub\022/\n\017RegisterReading\022\017.sensor.Reading" +
      "\032\013.sensor.Ack\0228\n\016StreamReadings\022\023.sensor" +
      ".SensorQuery\032\017.sensor.Reading0\001\0222\n\014Compu" +
      "teStats\022\023.sensor.SensorQuery\032\r.sensor.St" +
      "atsB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sensor_Reading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensor_Reading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensor_Reading_descriptor,
        new java.lang.String[] { "SensorId", "Type", "Value", "Timestamp", });
    internal_static_sensor_Ack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sensor_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensor_Ack_descriptor,
        new java.lang.String[] { "Accepted", "Message", });
    internal_static_sensor_SensorQuery_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sensor_SensorQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensor_SensorQuery_descriptor,
        new java.lang.String[] { "SensorId", "MaxResults", });
    internal_static_sensor_Stats_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sensor_Stats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensor_Stats_descriptor,
        new java.lang.String[] { "SensorId", "Count", "Average", "Max", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
