// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sensor.proto
// Protobuf Java Version: 4.31.1

package sensor;

@com.google.protobuf.Generated
public interface SensorQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor.SensorQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>int32 max_results = 2;</code>
   * @return The maxResults.
   */
  int getMaxResults();
}
