// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sensor.proto
// Protobuf Java Version: 4.31.1

package sensor;

@com.google.protobuf.Generated
public interface StatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor.Stats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>double average = 3;</code>
   * @return The average.
   */
  double getAverage();

  /**
   * <code>double max = 4;</code>
   * @return The max.
   */
  double getMax();
}
