# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genModelSelector.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'genModelSelector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16genModelSelector.proto\x12\nesame_sett\"O\n\x07Request\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08taskType\x18\x02 \x01(\t\x12\x0f\n\x07prompts\x18\x03 \x03(\t\x12\x11\n\tnumPrompt\x18\x04 \x01(\x05\"!\n\x06Result\x12\x17\n\x0f\x63onfidenceCheck\x18\x01 \x01(\x08\x32N\n\x10GenModelSelector\x12:\n\rsubmitGenTask\x12\x13.esame_sett.Request\x1a\x12.esame_sett.Result0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genModelSelector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=38
  _globals['_REQUEST']._serialized_end=117
  _globals['_RESULT']._serialized_start=119
  _globals['_RESULT']._serialized_end=152
  _globals['_GENMODELSELECTOR']._serialized_start=154
  _globals['_GENMODELSELECTOR']._serialized_end=232
# @@protoc_insertion_point(module_scope)
