# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_manager.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'order_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_manager.proto\x12\x0corderManager\"]\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scrizione\x18\x03 \x01(\t\x12\x0e\n\x06prezzo\x18\x04 \x01(\x02\x12\x14\n\x0c\x64\x65stinazione\x18\x05 \x01(\t\"=\n\x10\x43ombinedShipment\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05stato\x18\x02 \x01(\t\x12\x0e\n\x06ordini\x18\x03 \x01(\t\"\"\n\rStringMassage\x12\x11\n\tmessaggio\x18\x01 \x01(\t2\xe4\x02\n\x0cOrderManager\x12<\n\x08\x61\x64\x64Order\x12\x13.orderManager.Order\x1a\x1b.orderManager.StringMassage\x12<\n\x08getOrder\x12\x1b.orderManager.StringMassage\x1a\x13.orderManager.Order\x12\x42\n\x0csearchOrders\x12\x1b.orderManager.StringMassage\x1a\x13.orderManager.Order0\x01\x12H\n\rprocessOrders\x12\x13.orderManager.Order\x1a\x1e.orderManager.CombinedShipment(\x01\x30\x01\x12J\n\x0e\x63\x61ncelShipment\x12\x1b.orderManager.StringMassage\x1a\x1b.orderManager.StringMassageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=37
  _globals['_ORDER']._serialized_end=130
  _globals['_COMBINEDSHIPMENT']._serialized_start=132
  _globals['_COMBINEDSHIPMENT']._serialized_end=193
  _globals['_STRINGMASSAGE']._serialized_start=195
  _globals['_STRINGMASSAGE']._serialized_end=229
  _globals['_ORDERMANAGER']._serialized_start=232
  _globals['_ORDERMANAGER']._serialized_end=588
# @@protoc_insertion_point(module_scope)
